### ISSUE TITLE
[1.7.10] Crash with Immersive Engineering mod

### ISSUE THREAD

**Issue by Sinhika** [SpitefulFox/RidiculousWorld#4]
Found your repo. Ridiculous World & Immersive Engineering together crash Minecraft on launch.

Log here: http://pastebin.com/CnfENEf8

**Comment by SpitefulFox** [comment]
You're using an outdated version of the mod.

**Comment by Sinhika** [comment]
I have no idea how that happened, but updating to 0.4 fixed the problem.
