### ISSUE TITLE
Game Crash 

### ISSUE THREAD

**Issue by HiimAlviin** [SpitefulFox/RidiculousWorld#6]
https://pastebin.com/b7vms7rV

check this and help pls :D

**Comment by SpitefulFox** [comment]
The crash report very clearly points at Immersive Engineering.  I don't even see Ridiculous World as one of the mods installed on your list.

**Comment by HiimAlviin** [comment]
yeah but why xD?
latest forge for 1.7.10 and latest immersiv engineering ^^
i testet diverent versions of immersiv engineering x.x

**Comment by SpitefulFox** [comment]
The problem is with your config. You're using an invalid potion ID.  You'd be better off asking the actual author of Immersive Engineering instead of some random guy.

**Comment by SpitefulFox** [comment]
The actual author of the mod you're actually having trouble with suggests deleting your potion config, btw.
